# Stage 1 - the build process
FROM node:16 as build-deps
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . ./
RUN npm run build

# Stage 2 - the production environment
FROM node:16-alpine
WORKDIR /usr/src/app
COPY --from=build-deps /usr/src/app .
RUN npm install -g serve
EXPOSE 8000
CMD ["serve", "-s", "build", "-l", "8000"]