FROM node:16-alpine

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY . ./

RUN npm run build
RUN npm install -g serve

EXPOSE 5173

CMD ["npm", "run", "dev",  "--", "--host", "0.0.0.0", "--port", "5173"]